### PR TITLE
Add Swift Package Manager Support

### LINKED ISSUE #77: Swift Package Manager
SPM being included in Xcode 11 means we'll likely see a lot of demand for support. A Swift.package should be added to support this.

### PR DESCRIPTION
**Pull request by maxep**
### Issue Link :link:

Fixes #77

### Goals :soccer:

Add support of [Swift Package Manager](https://swift.org/package-manager/).

### Implementation Details :construction:

- As ClusterKit is implemented in objc, the project needs to follow the C library structure:
```
    . 
    ├── Package.swift
    └── Sources 
         └── ClusterKit
           ├── **/*.m
           └── include 
             ├── ClusterKit 
             | └── *.h
             └── module.modulemap
```

- In order to be built by `swift build` (macOS), `UIKit` availability has to be checked using compile fag:
```objective-c
#if __has_include(<UIKit/UIKit.h>)
...
#endif
```

- Replace `#import "*.h"` with module import `#import <ClusterKit/*.h>`.

### Testing Details :mag:
Test suite is not yet available at `swift test`, tests will need to be re-rewritten in swift.

### CODE REVIEW

**Comment by carbonimax** [comment]
It's all good but `mapView.clusterManager` seems to be not exposed to swift.

Error

**Comment by maxep** [comment]
@carbonimax It's using a custom [module.modulemap](https://github.com/hulab/ClusterKit/blob/feature/swift-package-manager/Sources/ClusterKit/include/module.modulemap) for SPM. You need to import the submodule:
```swift
import ClusterKit.MapKit
```

**Comment by carbonimax** [comment]
I missed it! It works

**Comment by thothai94** [comment]
How can I import this ClusterKit package to use with Mapbox?
"import ClusterKit.Mapbox" or "import ClusterKit" always cause error "Value of type 'MGLMapView' has no member 'clusterManager'"

**Pull request merged**
